### ISSUE TITLE
Use default value if backupFactor is not set in placement policy

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api-go#156]
Placement policy with `backupFactor = 0` produces empty placement.  Users can omit container backup factor value in their policies, therefore `netmap.GetCotnatinerNodes()` should use default `backupFactor` value in this case. It is proposed to set default `backupFactor` to 3.

cc: @fyrchik @realloc

**Comment by realloc** [comment]
Should we set the default in `neofs-api` to achieve the same behaviour for all?

**Comment by alexvanin** [comment]
@realloc Protocol buffer language v3 does not support constants as top level definitions. How do you propose to set it in `neofs-api`?

**Comment by realloc** [comment]
As a comment in description that will be reflected in Spec + set of test to verify correct implementation.
