### ISSUE TITLE
Make well known object search queries for user and system context

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api-go#163]
Object search method  without filters returns:
1. regular split object ids,
2. regular non-split object ids,
3. virtual object ids (big object ids that split into several regular split objects),
4. tombstone ids,
5. storage group ids.

There are at least two search scopes used in NeoFS:
- system scope,
- user scope.

**System** scope works with **(1)**, **(2)**, **(4)**, **(5)**. It is used by replication daemon for example. **User** scope works with **(2)**, **(3)**.

SDK should provide separate search wrapper functions for both of these scopes. These wrappers append provided filters with some well-known ones to get ids from above.

**Comment by cthulhu-rider** [comment]
Given the small set of selectors needed for system things, we can define a reserved system filter prefix
`const ReservedSystemPrefix = "$Object="`
and a set of system selectors (from desc):

1. `const KeyRegular = ReservedSystemPrefix + "Regular"`;

1. `const KeyNonSplit = ReservedSystemPrefix + "NonSplit"`;

1. `const KeyVirtual = ReservedSystemPrefix + "Virtual"`;

1. `const KeyTombstone = ReservedSystemPrefix + "Tombstone"`;

1. `const KeyStorageGroup = ReservedSystemPrefix + "StorageGroup"`.

Any filter with key that has prefix `ReservedSystemPrefix` is processed in a special way, all other filters are applied to custom attributes.

**Comment by alexvanin** [comment]
@cthulhu-rider These are five non intersecting sets. So if we provide two filters for user scope:
```
f := []Filters{ {name:KeyNonSplit}, {name: KeyVirtual} }
```

we will have empty set as a result, don't we?

**Comment by cthulhu-rider** [comment]
> @cthulhu-rider These are five non intersecting sets. So if we provide two filters for user scope:
> 
> ```
> f := []Filters{ {name:KeyNonSplit}, {name: KeyVirtual} }
> ```
> 
> we will have empty set as a result, don't we?

@alexvanin, yes, applying mutually exclusive filters on a request will result in an empty response, as expected.

**Comment by alexvanin** [comment]
> @alexvanin, yes, applying mutually exclusive filters on a request will result in an empty response, as expected.

In this case how does filter(s) for user scope will look like? It should be combined set of `KeyNonSplit` and `KeyVirtual`?

**Comment by cthulhu-rider** [comment]
> > @alexvanin, yes, applying mutually exclusive filters on a request will result in an empty response, as expected.
> 
> In this case how does filter(s) for user scope will look like? It should be combined set of `KeyNonSplit` and `KeyVirtual`?

@alexvanin, i'm not sure we need to differentiate between splitted and indivisible user objects. So `KeyVirtual` will cover all user objects, and `KeyNonSplit` is not needed.

**Comment by cthulhu-rider** [comment]
> > @alexvanin, yes, applying mutually exclusive filters on a request will result in an empty response, as expected.
> 
> In this case how does filter(s) for user scope will look like? It should be combined set of `KeyNonSplit` and `KeyVirtual`?

@alexvanin, I think we need two non-mutually exclusive filters:

1. `KeyRoot` - for initially stored objects;

1. `KeyLeaf` - for physically stored objects.

I'm not sure we need to differentiate virtual root objects from physically stored root objects, what do you think?

**Comment by alexvanin** [comment]
> I'm not sure we need to differentiate virtual root objects from physically stored root objects, what do you think?

@cthulhu-rider Probably there is no reason to separate virtual and physically stored root objects, I agree. Differentiate root objects and physically stored objects should be enough.

**Comment by alexvanin** [comment]
Closed by https://github.com/nspcc-dev/neofs-api-go/pull/164 and https://github.com/nspcc-dev/neofs-node/pull/54
