### ISSUE TITLE
Simplify structure unmarshaling for SDK users

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api-go#168]
There is an straightforward way to serialize SDK structure by converting it into unified structure and then using stable marshaler on it.

```go
data, err := bearerToken.ToV2().StableMarshal(nil)
```

But there is not simple way to convert it back. To do that, user has to use transport structure even though it is not necessary, because unified structures are matched with protobuf definition. 

```go
grpcToken := new(grpcACL.BearerToken)
err = grpcToken.Unmarshal(data)  // we can omit that

v2Token := v2ACL.BearerTokenFromGRPCMessage(grpcToken)
bearerToken := token.NewBearerTokenFromV2(v2Token)
```

The issue is that unlike stable marshallers, unmarshallers are a little more complicated. And we don't have to make them stable (with strict field order check in binary message) at all. Can we just hide GRPC or any other transport layer behind `Unmarshal()` function in `v2/*` packages?

**Comment by cthulhu-rider** [comment]
I think we can. [Here](https://github.com/nspcc-dev/neofs-api-go/blob/ad0b01e892dd4d8a9b4c92082caece27d5663462/v2/refs/marshal.go#L145) is an example. We can disseminate this approach to all `v2` messages. `StableUnmarshal` can be renamed to `Unmarshal` (or `UnmarshalBinary` to implement `encoding.BinaryUnmarshaler`).
