### ISSUE TITLE
What to do if nonce != uuid.Size?

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api-go#194]
I think the question deserves a separate issue: what we do if `len(GetNonce) != uuid.Size`?

_Originally posted by @cthulhu-rider in https://github.com/nspcc-dev/neofs-api-go/pull/193#discussion_r522718466_

This can happen if faulty client created such v2 structure or faulty node returned such container. Should we make sanity checks when parsing structure?

**Comment by realloc** [comment]
The spec says nonce is UUIDv4. If it's not, then it's invalid and must be rejected.

**Comment by cthulhu-rider** [comment]
This is a server-side issue, I suggest to reopen it in node.
