### ISSUE TITLE
Close function in clients

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api-go#196]
by @cthulhu-rider 

If client is created without provided connection, then it creates connection by itself. However there is no methods to close with that connection, so it will remain active even if client is already dropped. It would be nice to have `Close()` function to revoke client's connection.

**Comment by alexvanin** [comment]
I also propose to add function to check client's underlying connection. Something like `func (c *Client) IsAlive() bool`. This would be useful to maintain group of clients and recreate them on demand.

**Comment by fyrchik** [comment]
What's the use-case for `IsAlive`? According to https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md `TRANSIENT_FAILURE` isn't actually a "lost connection", as it attemts to reconnect. And `SHUTDOWN` is user-initiated `Close()`, before which we, probably, should already remove client from cache.

**Comment by alexvanin** [comment]
> What's the use-case for `IsAlive`? According to https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md `TRANSIENT_FAILURE` isn't actually a "lost connection", as it attemts to reconnect. And `SHUTDOWN` is user-initiated `Close()`, before which we, probably, should already remove client from cache.

The use-case is to check underlying client connection in client cache to drop client if server side died for some reason. We are not tied with gRPC transport in general, however we use only it right now. 

However it seems that there are no point in making some sort of `IsAlive()` or `Close()` functions if client will be able to return raw connection. We can provide connection in client constructor, why couldn't we get it back from client then? This way executing context could do whatever it wants with the connections: check state or even close it.
