### ISSUE TITLE
modo: Make to split info error constructor to return a pointer

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-api-go#221]
In current modo split info error [constructor](https://github.com/nspcc-dev/neofs-api-go/blob/eccdf294f1dc0450a18ec2d66297a6e0c9120f80/pkg/object/error.go#L17) returns struct type. This error type is going to be used in `errors.As` function, so it was convenient to `be a pointer to an interface or a type implementing error` to meet the function requirement.

Additionaly it would also be convenient to have a blank instance constructor.

**Comment by alexvanin** [comment]
Fixed in #223
