### ISSUE TITLE
Adopt well-known request x-headers from neofs-api

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api-go#241]
Adopt changes from https://github.com/nspcc-dev/neofs-api/issues/117

SDK client should be able to set custom values for all object related requests.

Default values for get, head, search, range and range hash operations are `0/1` where `1` is a lookup depth, and `0` is an epoch number. 

Default values for put and delete operations are `0/0`.

**Comment by cthulhu-rider** [comment]
I suggest leaving the defaults to zero in the client to keep the default behavior.

**Comment by alexvanin** [comment]
Let's keep `pkg/client` default well-known request x-header values with `0/0` and come back to it before next release.

**Comment by alexvanin** [comment]
Default values for client gonna be `0\0`. The user can set up custom values via x-headers. Later CLI can support some global arguments to set these well-known x-header values.
