### ISSUE TITLE
Implement `String()` and `Parse()` for version-independent types.

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-api-go#310]
This is a nice thing to have and costs us nothing (at least for `String()`). This facilities can be reused in JSON (un)marshaling routines.
I have already implemented this ad-hoc 2 times (for placement policy output with v2netmap types and for eacl in nspcc-dev/neofs-td#4).

**Comment by cthulhu-rider** [comment]
@fyrchik can you give an example for what specific type do you expect string methods? Enums I suppose.

**Comment by fyrchik** [comment]
Yes only enums: `eacl.Operation`, `netmap.OpEQ` etc. I expect stringers for such types to be present by default.

**Comment by cthulhu-rider** [comment]
We can also implement stdlib `binary.TextMarshaler` / `binary.TextUnmarshaler` interfaces on enums to straighten the text format. This will allow you to leave more freedom in the implementation of `fmt.Stringer` interface.
