### ISSUE TITLE
Provide io.Reader interface to object payload (whole or range)

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-api-go#313]
To fix nspcc-dev/neofs-http-gw#67 we need some API that will provide `io.Reader` interface to payload data, something like:
```
    reader, err = client.GetPayloadReader(ctx, options)...
    _, err = io.Copy(writer, reader)
```
I think we'll make a separate `GetHeader` request anyway, so combining it with some actions for headers (either in returned value or in callback) is not critical.

**Comment by cthulhu-rider** [comment]
To avoid breaking the current behavior, I suggest for the first time such parameters:
```
func (p *GetObjectParams) WithHeaderHandler(func(head *object.Object))
```
if provided -> called immediately when header is read.

```
func (p *GetObjectParams) WithPayloadReaderHandler(func(io.Reader))
```
if provided -> `io.Reader` is formed and passed to handler (overwhelms payload writers).

**Comment by roman-khimov** [comment]
I don't think it'll help with fasthttp. We need some `io.Reader` _after_ `GetObject` completion there.

**Comment by cthulhu-rider** [comment]
@roman-khimov this should work for your case (if I correctly understood fasthttp):
```
header, _ = c.GetObject(ctx, new(GetObjectParams).
  ...
  WithPayloadReaderHandler(func(r io.Reader) {
    fasthttp.SetReader(rdr)
  })
)
```

**Comment by roman-khimov** [comment]
OK, we'll try that.
