### ISSUE TITLE
Update go version

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api-go#387]
go1.16 is not supported after go1.18 release.

**Comment by cthulhu-rider** [comment]
How we want to upgrade Go version in lib?

**Comment by alexvanin** [comment]
At first I thought that we will keep in sync go versions of neofs-node and corresponding api-go / sdk-go libraries. 

However it might not be necessary, because lib doesn't have to follow the same security concerns as application and it may benefit from long-time support for 3rd party apps. So we can avoid update until there will be explicit reasons for (performance \ security breach \ something else).

**Comment by roman-khimov** [comment]
It's up to date now at 1.19.
